### ISSUE TITLE
Nameplates Scale

### ISSUE THREAD

**Issue by Noob1e** [bkader/TidyPlates_WoTLK#2]
1) Threat System scales overrides the target nameplate scale.

I got target scale at 110% but it's still using the threat scales (100%) on current the target.

![WoWScrnShot_060621_122918](https://user-images.githubusercontent.com/27544010/120919663-6deb6d80-c6c3-11eb-89b3-ac9c1c750da2.jpg)
![WoWScrnShot_060621_122925](https://user-images.githubusercontent.com/27544010/120919664-6f1c9a80-c6c3-11eb-8da4-385a7152f160.jpg)

2) Is it possible to change transparency of the nameplates? I mean, the missing health parts of nameplates are totally transparent so I would like to make them 50-75% black. Just like KUI or ElvUI nameplates.

**Comment by bkader** [comment]
I updated the addon, can you give it a try?
* I added a 75% dark background.
* I made sure the higher scale is used, so no scale should override the other.

**Comment by Noob1e** [comment]
Everything looks fine now. Thank you :)
