### ISSUE TITLE
suggestion border objetive and option message welcome

### ISSUE THREAD

**Issue by abel8909** [bkader/TidyPlates_WoTLK#3]
two suggestion
  - Add border color healthbar in "Target Highlight", example like over mouse (I attach the example image)
  - option to disable the chat message "Threath Plates: Welcome Back"
  
![asdasdsad](https://user-images.githubusercontent.com/89325544/134039889-c24dae8f-4009-4f71-9ebc-6adff0d25f2d.png)

**Comment by bkader** [comment]
For question 1: it requires a bit of rewrite that's not really "urgent", so I will skip for now.
As for question 2: use the command `"/tptpverbose"`
