### ISSUE TITLE
Instant Cast Spells

### ISSUE THREAD

**Issue by Noob1e** [bkader/TidyPlates_WoTLK#4]
**Version:** 5.6

**Issue:** I'm using Threat Plates. It's showing instantly casted spells by enemy players (like Flash of Light, Pyroblast, Lava Burst etc.) on their castbars then the castbar disappears after 0.2-0.3 seconds.

**Comment by bkader** [comment]
Hello @Noob1e, sorry for my late answer.

https://user-images.githubusercontent.com/4732702/136677954-a72a0bd4-9fa1-40a2-b12a-2c3584437257.mp4

I have tried several times to see if castbars for instant spells appear or not but I failed. I couldn't reproduce the issue sadly. I haven't slowed the video to check if the bar shows for few milliseconds but visually it didn't appear to me I don't know why.

**Comment by Noob1e** [comment]
Hello Kader. First of all, thank you for your efforts :)
I see this issue is mostly with non-target nameplates in battlegrounds. I'm not sure if I can record any video because of my old PC but I'll try to do it anyway.

**Comment by bkader** [comment]
Hello again! After some digging I noticed that (_which should've been obvious_) that the combat log provides nothing but `SPELL_CAST_START` and that's why spells on non-targets start but don't stop when they fail, stop or are interrupted. Leave this issue opened for now, I will later try some approaches an hopefully I can make it work.
To reproduce what I am talking about: mouseover a unit to cache it onces, then make it cast and stop and you will see on the other hand that the castbar continues anyways.

**Comment by Noob1e** [comment]
Well, looks like you found a way to fix instant spell casts but now the nameplates doesn't show some spell cast bars filled and sometimes they get stuck.

Edit: This can be seen more often in Battlegrounds.

![WoWScrnShot_050222_160457](https://user-images.githubusercontent.com/27544010/166890308-54bec44f-665e-4007-9a50-57ee1798d546.jpg)
Cast bar doesn't get filled

![WoWScrnShot_050222_160453](https://user-images.githubusercontent.com/27544010/166890829-f2979a92-3432-4d4f-a63f-adc81c1e8994.jpg)
Cast bar got stuck

**Comment by Noob1e** [comment]
This new bug is much worse tbh. Old version was better.

**Comment by bkader** [comment]
> This new bug is much worse tbh. Old version was better.

I will check the problem as soon as possible.

**EDIT**
I sadly couldn't reproduce the problem, I did all possible dungs/raids where there are casters. I will wait until I encounter the issue and know how it happens.

**Comment by Noob1e** [comment]
The problem is that castbar stucks on spell casting. Sometimes it doesn't show the castbar but displays the spell name and sometimes it shows both but stucks. It only gets fixed if I click on that nameplate.

I'll try to take more video records but this is all I have right now.
https://streamable.com/sxgbnu

**Comment by bkader** [comment]
## Known GUID

https://user-images.githubusercontent.com/4732702/168450941-3d9fe56f-e191-4c56-8721-2326fccb1ed0.mp4

## Unknown GUID

https://user-images.githubusercontent.com/4732702/168450959-952e061b-6962-4823-9be6-5321d83d9014.mp4

_Both tests were done on a regular client with only `Wow.exe` from the HD client_.

**Comment by Noob1e** [comment]
I also use HD wow.exe (not mpq files). The problem still persists for me. Sometimes, I still can't see the cast bar or the cast bar gets stuck. There was no such problem before instant casting fixes.

Maybe our wow.exe are different. Can you upload your exe, please?

**Comment by bkader** [comment]
I am pretty sure we are using the same exe file, but just in case, I shared it on Discord or you can get it [from here](https://cdn.discordapp.com/attachments/828003690257448969/965750259701661707/Wow.exe)

**Comment by Noob1e** [comment]
I also tried with your wow.exe in dungeons, battlegrounds and arenas but unfortunately it's still the same.

![WoWScrnShot_052222_213305](https://user-images.githubusercontent.com/27544010/169710489-31b96a4a-d720-4ffa-a920-de02cab60679.jpg)
These "Shoot"s in the screenshot don't actually have a casting time, but they show up in the castbar and get stuck.

The screenshot was taken in Storm Peaks at coordinates 36, 64.

**Comment by bkader** [comment]
@Noob1e update the addon and see if the problem is gone. I went to that location and could reproduce it. Let's hope the few lines I added fixes the issue, it fixed it for me.

**Comment by Noob1e** [comment]
I tried it at the same location and battlegrounds. Everything looks good now. Thanks @bkader  :)

**Comment by bkader** [comment]
Thanks for testing it @Noob1e. I can finally sleep in peace.
