### ISSUE TITLE
attempt to index field 'db' (a nil value)

### ISSUE THREAD

**Issue by DimaSheiko** [bkader/TidyPlates_WoTLK#7]
Hi, after the last updates I have been experiencing a lot of errors with TidyPlates as soon as the game starts. This started after the [AC3 library was updated](https://github.com/bkader/TidyPlates_WoTLK/commit/dc7a7999a17632ca5b3d21f1a38012691dbd1fe3) along with many other addons. Several addons like give errors with the AC3 library 
ElvuiProject Zildras: `Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119`
Details: `Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119`
ElvUI_AddOnSkins: `Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145`
Postal: `AceAddon-3.0-13:70: in function <...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>`
KRU: `\Modules\Invites.lua:301: attempt to index local 'self' (a nil value)
<in C code>: ?
AceAddon-3.0-13:70: in function <...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65`
And many more

Basically my BugSnack gets full of them and every now and then it warns me that there are more errors. Here is a log of what bugsnack tells me.

```
1x TidyPlates_ThreatPlates-5.7\Core.lua:1328: attempt to index field 'db' (a nil value)
<in C code>: ?
<in C code>: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:235: in function `UIParentLoadAddOn':
Interface\FrameXML\UIParent.lua:309: in function `TimeManager_LoadUI':
Interface\FrameXML\InterfaceOptionsPanels.lua:580: in function `setFunc':
Interface\FrameXML\InterfaceOptionsPanels.lua:571: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:564>:

Locals:
(*temporary) = "Blizzard_TimeManager"
(*temporary) = "ADDON_LOADED"
(*temporary) = "Blizzard_TimeManager"
(*temporary) = "ADDON_LOADED"
(*temporary) = "Blizzard_TimeManager"
(*temporary) = InterfaceOptionsDisplayPanel {
 controls = <table> {}
 cancel = <function> @ Interface\FrameXML\InterfaceOptionsPanels.lua:86:
 name = "Mostrar"
 default = <function> @ Interface\FrameXML\InterfaceOptionsPanels.lua:95:
 0 = <userdata>
 refresh = <function> @ Interface\FrameXML\InterfaceOptionsPanels.lua:104:
 okay = <function> @ Interface\FrameXML\OptionsPanelTemplates.lua:277:
 options = <table> {}
}
(*temporary) = "PLAYER_ENTERING_WORLD"
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1

  ---
```

![image](https://user-images.githubusercontent.com/67640628/164914514-89585d8d-5fda-45d2-9327-94ad27504205.png)

**Comment by bkader** [comment]
Hello @DimaSheiko . You have answered your own question. You started encountering issues after you update Ace3 or whatever addons you updated, TidyPlates is working just fine without any lib updates, so you need to check your addons one by one to see what's causing the issue. Try with only tidyplates/threatplates, if the error disappears then it's from another addon.

**Comment by DimaSheiko** [comment]
You are right, the error comes from another addon, sorry for the inconvenience, I thought it was from this one because of what bugsack tells me. Thank you
